### ISSUE TITLE
Words were shifted

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#14]
d["a4a_food"] for Russian are shifted. You add/delete/modify new words, but not in localized files.
It's important to have PO files to see both English and localized strings.
Depends on https://github.com/imiolek-ireneusz/eduActiv8/issues/8

**Comment by imiolek-ireneusz** [comment]
I found the issue and it is now fixed - will push it here soon. For some reason, I had one word twice, and another one was missing. For this list maybe not necessarily the PO, but I like the GCompris approach to it - a json type of a format. Will look into this when I get some spare time - for now it will work. Below are the matched words where the issue happened. Thanks for spotting this. Cookie word was missing I used "печенье" for it.
yoghurt : йогурт
dessert : десерт
pretzel : десерт
peanut : крендель
jam : арахис
feast : варенье
cookie : курица
bacon : бекон
spice : специи

**Comment by glixx** [comment]
JSON will not be localized. Translators do not like this format. But PO files is the best way. GCompris goes wrong way.
