### ISSUE TITLE
Similar games have different behavior

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#16]
Game №049/140 has correctness effect for each letter, but game №049/011 does not.

**Comment by imiolek-ireneusz** [comment]
The immediate autocorrection in both of those games stops at level 5 - so do the colour clues.
Can you please confirm you were on level 5 or above when testing the 049/011? or is there something else happening that I did not manage to spot?

**Comment by glixx** [comment]
I did not check levels. This issue is invalid.
