### ISSUE TITLE
2 same games

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#19]
Games №111/042, №111/207 are same.

**Comment by imiolek-ireneusz** [comment]
Not sure what to do with this one. They are slightly different.
111/043 (there is no 111/042) - is only visible up to year 2. The numbers to sort consist of a set of consecutive numbers, ie. 3, 4, 5, 6, 7, so it's basically a matter of finding the minimum number and then finding the next number up until finished.
111/207 gives a random set of numbers from a range appropriate for the level, ie. 3, 5, 12, 18, 25 - in this case you don't know what number you are looking for, except that you constantly look for the minimum number, well unless you want to do it back to front.

**Comment by glixx** [comment]
I guess needs to add addition comment to have difference.
