### ISSUE TITLE
Enable Fraction Matching Game (102/242) in Russian

### ISSUE THREAD

**Issue by imiolek-ireneusz** [imiolek-ireneusz/eduActiv8#22]
Enable Fraction Matching Game (102/242) in Russian and confirm the 2 forms of plurals to spell out fractions is enough.
Do we need another form?
numerators = ['одна', 'две', 'три', 'четыре', 'пять', 'шесть', 'семь', 'восемь', 'девять', 'десять', 'одиннадцать', 'двенадцать']
d_singular = ['', 'вторая', 'третья', 'четвёртая', 'пятая', 'шестая', 'седьмая', 'восьмая', 'девятая', 'десятая', 'одиннадцатая', 'двенадцатая']
d_plural = ['', 'вторых', 'третьих', 'четвёртых', 'пятых', 'шестых', 'седьмых', 'восьмых', 'девятых', 'десятых', 'одиннадцатых', 'двенадцатых']

**Comment by glixx** [comment]
> Do we need another form?
No.

> Enable Fraction Matching Game (102/242) in Russian
It works fine. Many thanks.

**Comment by imiolek-ireneusz** [comment]
That's brilliant, thanks for checking.
