### ISSUE TITLE
ambiguous python shebang

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#24]
Fedora Rawhide:

*** ERROR: ambiguous python shebang in /usr/share/eduactiv8/eduactiv8.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.

**Comment by imiolek-ireneusz** [comment]
I suppose it can only be python3 since python2 is slowly going to be phased out.
I will update that soon.

**Comment by glixx** [comment]
grep -r "env python"

eduactiv82exe.py:#!/usr/bin/env python
cleanup.py:#!/usr/bin/env python
eduactiv8.py:#!/usr/bin/env python3
classes/xml_conn.py:#!/usr/bin/env python

eduactiv8.noarch: W: non-executable-script /usr/share/eduactiv8/classes/xml_conn.py 0664 /usr/bin/env
