### ISSUE TITLE
Build packages for linux

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#25]
Future proposal:

To be more popular it's good to provide packages for linux. There is build.opensuse.org , that allows to build at least RPM, DEB, Arch Linux.
RPM: spec file from Mageia Linux will allow you to build RPM packages for many RPM-based distros. Just upload source, spec file, and service will build packages automatically.
DEB: needs to adapt specifications from pysiogame: http://ftp.br.debian.org/debian/pool/main/p/pysiogame/
ARCH: needs to write PKGBUILD only. It is easy. Any template and all commands from SPEC file.

What do you think?

**Comment by glixx** [comment]
RPM results (after fix https://github.com/imiolek-ireneusz/eduActiv8/issues/24 ):
![screenshot_20190109_153008](https://user-images.githubusercontent.com/2681872/50878685-e6fa1400-13e8-11e9-9ad5-b915fda73c16.png)

**Comment by imiolek-ireneusz** [comment]
Looks interesting. The picture above shows to some extent how fragmented Linux is these days - quite a few distributions to maintain and upload with every release. I will have a proper look at this when I get a little bit more spare time.

**Comment by glixx** [comment]
Done: https://build.opensuse.org/package/show/home:loginov_alex_valer/eduactiv8
Just register there, copy to you and rebuild after 4.19.01 release.
Arch Linux was built using "Arch:Community/standard" repo only.
Needs to test resulted packages.

**Comment by glixx** [comment]
Done.
https://pkgs.org/download/eduactiv9
https://build.opensuse.org/package/show/home:loginov_alex_valer/eduactiv8
OBS has issue. To be sure packages were built correctly needs to delete all built binaries before new building and up rel (pkgrel, Release, Version).
Arch Linux cannot be built using python3-pygame at the moment, they have python2-pygame only (just to wait them).

**Comment by glixx** [comment]
Arch linux should have python3-pygame, but needs to find repository. If it is missing really, then to modify /usr/bin/aduactiv8 using sed while building for python2.

**Comment by imiolek-ireneusz** [comment]
Just tried installing on Ubuntu 16.04, 18.04 and Linux Mint 19 (trying xUbuntu_18.04 version).

Unfortunately, I was not very successful. We may either need to drop down to python2 or find a new way of getting pygame for python3 automatically installed. There does not appear to be a python3-pygame package available on Debian based distros.

dpkg log:
Preparing to unpack .../eduactiv8_4.19.01-1_all.deb ...
Unpacking eduactiv8 (4.19.01-1) ...
dpkg: dependency problems prevent configuration of eduactiv8:
 eduactiv8 depends on python3-pygame; however:
  Package python3-pygame is not installed.
 eduactiv8 depends on espeak; however:
  Package espeak is not installed.

dpkg: error processing package eduactiv8 (--install):
 dependency problems - leaving unconfigured

On Debian website, the python3-pygame package does not appear to be stable yet:
https://packages.debian.org/search?keywords=python3-pygame

At the moment people seem to be installing pygame for python3 via pip:
https://stackoverflow.com/questions/42707566/how-to-install-pygame-for-python3-5-in-ubuntu16-04

**Comment by glixx** [comment]
Did you enable Ubuntu Proposed Universe repository?

**Comment by glixx** [comment]
Debian Main has python3-pygame. So it goes to Ubuntu Universe with delay.

**Comment by imiolek-ireneusz** [comment]
Tried enabling it but still no luck. Same issue.
![virtualbox_ubuntu 18](https://user-images.githubusercontent.com/6198330/51268841-d7666680-19b8-11e9-8a8d-b48d9e21157f.png)

**Comment by glixx** [comment]
What is about Debian?

**Comment by imiolek-ireneusz** [comment]
No idea, but it may be just easier to run it in python2. And just update in a few years time, when python3 is finally fully supported.

When I get a chance I'll download a Debian installer and test it on one of them as well.

**Comment by glixx** [comment]
I guess needs to test on Debian first. If program will be unstable or installation will be hard, then to have more arguments to switch on python2 by default back.

**Comment by glixx** [comment]
Debian 10 has python3-pygame in Main repo.

**Comment by glixx** [comment]
Let's switch on python2 back.
eduactiv8 and eduactiv8.py

**Comment by imiolek-ireneusz** [comment]
Will switch back to python2 when I get back to the PC for a bit longer, which again is probably going to be after the weekend.
The program works fine with python3 when run directly from source with pygame for python installed via pip3.

**Comment by imiolek-ireneusz** [comment]
OK, looks like I managed to install the eduactiv8 package on the latest Debian, but had to install the required software separately. Used the package built for Debian 9 though.
Log below:

root@debian:/home/irek# sudo apt-get install python3-pygame
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fonts-freefont-ttf libmad0 libmikmod3 libportmidi0 libsdl-image1.2
  libsdl-mixer1.2 libsdl-ttf2.0-0 libsdl2-2.0-0 python3-numpy
Suggested packages:
  gcc gfortran python-numpy-doc python3-dev python3-pytest python3-numpy-dbg
  python-pygame-doc timidity
The following NEW packages will be installed:
  fonts-freefont-ttf libmad0 libmikmod3 libportmidi0 libsdl-image1.2
  libsdl-mixer1.2 libsdl-ttf2.0-0 libsdl2-2.0-0 python3-numpy python3-pygame
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,809 kB of archives.
After this operation, 28.8 MB of additional disk space will be used.
(...)
root@debian:/home/irek# dpkg -i /home/irek/Downloads/eduactiv8_4.19.01-1_all.deb
Selecting previously unselected package eduactiv8.
(Reading database ... 147093 files and directories currently installed.)
Preparing to unpack .../eduactiv8_4.19.01-1_all.deb ...
Unpacking eduactiv8 (4.19.01-1) ...
dpkg: dependency problems prevent configuration of eduactiv8:
 eduactiv8 depends on espeak; however:
  Package espeak is not installed.

dpkg: error processing package eduactiv8 (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.31.3-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.61) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.5-1) ...
Errors were encountered while processing:
 eduactiv8
root@debian:/home/irek# sudo apt-get install espeak
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 espeak : Depends: libespeak1 (>= 1.48.04+dfsg)
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@debian:/home/irek# apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  espeak espeak-data libespeak1 libportaudio2
The following NEW packages will be installed:
  espeak espeak-data libespeak1 libportaudio2
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 1,234 kB of archives.
After this operation, 3,019 kB of additional disk space will be used.
(...)
root@debian:/home/irek# apt-get install espeak
Reading package lists... Done
Building dependency tree       
Reading state information... Done
espeak is already the newest version (1.48.04+dfsg-7).
espeak set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@debian:/home/irek# dpkg -i /home/irek/Downloads/eduactiv8_4.19.01-1_all.deb
(Reading database ... 149345 files and directories currently installed.)
Preparing to unpack .../eduactiv8_4.19.01-1_all.deb ...
Unpacking eduactiv8 (4.19.01-1) over (4.19.01-1) ...
Setting up eduactiv8 (4.19.01-1) ...
Processing triggers for gnome-menus (3.31.3-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.61) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.5-1) ...
root@debian:/home/irek#

**Comment by glixx** [comment]
It looks good.

**Comment by imiolek-ireneusz** [comment]
Yes, sorry I didn't make it clear. After installing all the dependencies and the package itself the program works perfectly fine.

**Comment by glixx** [comment]
Switching on python2 by default?

**Comment by imiolek-ireneusz** [comment]
Yes, I will switch eduactiv8.py back to python2, but I think I'll go with the idea of earlier on. Since the program as such is compatible with both python2 and python3  I'll create a launcher main.py - need one of those for my Android debugging environment anyway - will save me from having to change the name before packaging. I'll also create a main3.py launcher to use with python3. And then when packaging for different distros depending on availability of pygame3-pygame package use appropriate launcher and the list of dependencies.

**Comment by imiolek-ireneusz** [comment]
The 2 files were added just as a workaround for the shebang issue (probably not necessary since we explicitly start it with python(2/3) command. Now I'm not sure how to go about checking for the availability of installed packages in the eduactiv8 shell script, temporarily added a probably unnecessary eduactiv8py3 file (since then everything else would need to change). Sorry, I've never really tried to package anything for any Linux distro, so my skills in that field are rather non-existent at the moment.

**Comment by glixx** [comment]
By my opinion needs to revert and just to change python3 on python2. Nothing more.
To use 'sed' while packaging to change python2 on python3 if it needed.

**Comment by imiolek-ireneusz** [comment]
I was actually thinking the same. I think I messed it up a bit. In fact, the Android version did not want to run from the new main.py file anyway, had to rename eduactiv8.py to main.py before building. Thanks.

**Comment by glixx** [comment]
New round for pkg testing. I rebuilt pkgs.

**Comment by imiolek-ireneusz** [comment]
Ubuntu dependencies need changing.
python2 needs to be python
python2-pygame needs to be changed to python-pygame.

Debian 10 seems to have python2 alias for python but no python2-pygame, just python-pygame, so may be easier and safer to just use the same dependencies as with Ubuntu.

License on Debian/Ubuntu says "Proprietary" - should be Free Software

**Comment by glixx** [comment]
Just for information.
You can use macroses for specific conditions on name of distrubution, version.
If names of dependencies will be different in future.

For example:

```
%if 0%{?mageia}
something
%endif
```

```
%if 0%{?fedora_version} || 0%{?centos_version}
something
%endif
```

```
%if 0%{?suse_version}
something
%endif
```

```
%if 0%{?suse_version} == 1315 && 0%{?is_opensuse}
something
%endif
```

```
%if 0%{?suse_version}
something
%else
something
%endif
```

**Comment by glixx** [comment]
Did you get files from https://build.opensuse.org/package/show/home:loginov_alex_valer/eduactiv8 ?
I don't see packages on https://www.eduactiv8.org/

**Comment by imiolek-ireneusz** [comment]
I only created a project on opensuse.org 3 days ago. Sorry, I've been a little bit busy lately.
I will add a link on eduactiv8.org as soon as the build packages show on the project. 
Is there anything I actually need to do for the software to show up on software.opensuse.org or is it automatically taken from the build? For some reason, nothing shows on my account.
https://software.opensuse.org//download.html?project=home%3Aimiolek-i&package=eduActiv8

But yours has all the packages there:
https://software.opensuse.org//download.html?project=home%3Aloginov_alex_valer&package=eduactiv8

With so many different distros, I think it would just be easier to link it to the software.opensuse.org, for people to select whichever method they like to use to install the thing.

And this is my build.* account:
https://build.opensuse.org/package/show/home:imiolek-i/eduActiv8

**Comment by glixx** [comment]
I see your packages by url https://software.opensuse.org//download.html?project=home%3Aimiolek-i&package=eduactiv8

> With so many different distros, I think it would just be easier to link it to the software.opensuse.org, for people to select whichever method they like to use to install the thing.

Yes.

I hope your program will be more popular.
And it's time for new release!

**Comment by imiolek-ireneusz** [comment]
Oh, I see, I shouldn't have used uppercase A in the name of the package. The "Download package" link from my build.* points to the URL with uppercase A, when it should be lowercase, never mind.

One more thing, I used all the files from your package, but for me, it doesn't build for Arch Linux, don't know why.

Time for a new release?
I don't think there's anything new to release. Unfortunately, since I started studying on top of my full-time job this project does not get as much love as it used to.

**Comment by glixx** [comment]
Needs to configure Arch Linux repository to use community repo only.
It's important to release and provide new packages.
I have plans to update Debian repository.

**Comment by imiolek-ireneusz** [comment]
OK, I see what you mean. I have released the latest changes to SourceForge, uploaded all changes here as well, but just did not create the actual release. I'll see if I have any changes on my end and will get it sorted.

**Comment by glixx** [comment]
![Screenshot_20190416_224213](https://user-images.githubusercontent.com/2681872/56248804-328c2000-60b2-11e9-9f8b-00575e2f97df.png)

**Comment by glixx** [comment]
You used my d4b2fba9861a1407c0b5083746833f51 17164 eduactiv8-4.19.01.tar.gz, but it's not release, but testing.

**Comment by imiolek-ireneusz** [comment]
An interesting experience trying to get this thing to work, but I think I managed to get it updated with the latest release (4.19.02) on the Build Service, however, with my very limited knowledge about packaging I may have messed it up.

Initially I used your version (4.19.01), because I could not figure out how to generate all the configuration files, but I ended up changing the version numbers, sha values and sizes manually and it seemed to build eventually.

**Comment by glixx** [comment]
Configuration files are already written.

> but I ended up changing the version numbers, sha values and sizes manually and it seemed to build eventually.

Yes. It's easy.

**Comment by imiolek-ireneusz** [comment]
> Yes. It's easy.
Well, now it seems that way (when I know what I'm supposed to be doing), but seeing all those "failed" next to most of the repos wasn't much fun (mainly again because of the uppercase letter in the filename).
Thanks again for all the setup you have done with this - it's all building beautifully, even the Arch Linux seems to be fine.

**Comment by glixx** [comment]
It's linux policy do not use capitalized letters for package names.

I just deleted i18n/custom/check_lists.py: http://svnweb.mageia.org/packages/cauldron/eduactiv8/current/SPECS/eduactiv8.spec?r1=1391866&r2=1391865&pathrev=1391866

My congratulations!

**Comment by imiolek-ireneusz** [comment]
That's great, thank you again.
Looks like the check_list.py is just an old conversion file I forgot to delete, but since everything builds ok I'll get it removed with next release.

**Comment by glixx** [comment]
Needs to add new versions of distributions in list of repositories.
