### ISSUE TITLE
non-standard-dir-perm

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#27]
Development branch:

eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/purple 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/connect 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/memory 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/pink 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons/schemes/cat_bg_star 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/classes/drw 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/score_bar 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/info_bar 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/FreeSans 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/fruit_n_veg 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/fc 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/clothes_n_accessories 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icon 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/blue 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/themes/default 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/actions 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/jobs 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/i18n/custom/a4a_py 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/eduactiv8Fonts 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons/schemes/cat_bg_square 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/orange 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/info_bar/decor 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/olive 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/i18n/custom 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/transport 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/people 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/food 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/body 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/fr 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/info_bar/mask/old 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/themes 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/home_icons 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/themes/default/images 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/schemes/white 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons/schemes/cat_bg_hex 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/symmetry 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/green 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/i18n/custom/kbrd 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/dialog 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/LinLibertine/Kacst Licence 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/nature 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/i18n 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/game_boards 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons/schemes/game_bg 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/schemes/black/match_animals 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/schemes 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/shapes/yellow 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/not_used/KacstOne 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/match_animals 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/not_used 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons/schemes/cat_bg_circle 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/classes 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/i18n/custom/word_lists 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/sounds 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/icons/schemes 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/LinLibertine/LinBiolinum Licence 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/schemes/black 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/fish 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/animals 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/info_bar/mask 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/xml 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/fonts/LinLibertine 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/sport 0700
eduactiv8.noarch: E: non-standard-dir-perm (Badness: 1) /usr/share/eduactiv8/res/images/art4apps/construction 0700

Fix:

find ./ -type d -exec chmod 755 {} \;

**Comment by imiolek-ireneusz** [comment]
Not sure why they were 0700? Probably nobody except me needs access to those directories. Will do the chmod command over dirs.

**Comment by glixx** [comment]
Windows likes to change permissions. Probably you used sources in Windows.

**Comment by imiolek-ireneusz** [comment]
I don't think it would be anything to do with Windows. I work on Ubuntu, the source is only on Windows to do packaging, and comes back as a zip to the Ubuntu machine. Anyway, just changed the dirs to 755.

**Comment by glixx** [comment]
It looks issue of github. Github generates zip file with wrong permissions:
https://github.com/imiolek-ireneusz/eduActiv8/archive/master.zip
https://github.com/imiolek-ireneusz/eduActiv8/archive/development.zip

Bit "git clone" works correctly.

**Comment by glixx** [comment]
Needs to forward issue to github support.

**Comment by imiolek-ireneusz** [comment]
Looks like git does not seem to update changes to permissions other than the executable part.

Also not sure why you ended up with 700? Anything to do with unzipping software maybe? After downloading the zips I get 775 for directories, even though they are 755 on my local git repo. The non-executable files in zips are 664 unlike 644 on my end. Only executable files are correct 755 both in the zips and on my drive. 

Files after unpacking the zip
![Files from zip](https://user-images.githubusercontent.com/6198330/51110629-46915e80-17f1-11e9-9eeb-80d9bcf55954.png)

Files in my local repository:
![Files in local repo](https://user-images.githubusercontent.com/6198330/51110633-4d1fd600-17f1-11e9-8d5b-b7ef23b31f2f.png)

I downloaded a non-related repo to see what happens there and got the same result (775 for dirs and 664 for files). Looks like this is the standard set of permissions GitHub enforces.

**Comment by glixx** [comment]
Problem is Ark.
