### ISSUE TITLE
freefont package

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#28]
> You may also need to install a compatible version of the freefont package. Unfortunately, it has a different name under each platform:
fonts-freefont-ttf (Debian)
ttf-freefont (Ubuntu)
gnu-free-sans-fonts (Fedora)
or equivalent in your distro

1. Ubuntu has fonts-freefont-ttf like Debian (https://pkgs.org/download/fonts-freefont-ttf)
2. Do you really need freefont package if you have fonts in sources?

**Comment by imiolek-ireneusz** [comment]
I will get the Ubuntu one updated however I didn't need that on Ubuntu, but apparently, it was needed on Debian, not sure why, since I do not rely on any of those.

**Comment by imiolek-ireneusz** [comment]
Website updated.

**Comment by glixx** [comment]
fonts-freefont-ttf is requires of python-pygame on Debian and Ubuntu. So when you inslall python-pygame, then fonts-freefont-ttf will be installed automatically.
![screenshot_20190110_094330](https://user-images.githubusercontent.com/2681872/50936642-8ec32080-1481-11e9-8cee-10d34d195089.png)
Same for Fedora.
Anyway system fonts are not in use.

**Comment by glixx** [comment]
fonts-freefont-ttf package will be installed with eduactiv8 deb package, cause it was built specially to use system fonts-freefont-ttf.
Others do not need to install freefont package.

**Comment by imiolek-ireneusz** [comment]
Thanks for looking into this. I have removed the misleading bit of information about the freefont package from the website altogether.
