### ISSUE TITLE
Check MO files before using

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#35]
```
eduactiv8
Working directory: /usr/share/eduactiv8
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/share/eduactiv8/eduactiv8.py", line 649, in <module>
    main()
  File "/usr/share/eduactiv8/eduactiv8.py", line 639, in main
    app.run()
  File "/usr/share/eduactiv8/eduactiv8.py", line 354, in run
    self.set_up_user()
  File "/usr/share/eduactiv8/eduactiv8.py", line 223, in set_up_user
    self.lang.load_language()
  File "/usr/share/eduactiv8/classes/lang.py", line 44, in load_language
    self.get_lang_attr()
  File "/usr/share/eduactiv8/classes/lang.py", line 51, in get_lang_attr
    self.trans[self.lang] = gettext.GNUTranslations(open(filename, "rb"))
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/usr/share/locale/uk/LC_MESSAGES/eduactiv8.mo'
```
If file does not exist then do not switch on it and do not remember choice, just ignoring.

**Comment by imiolek-ireneusz** [comment]
This appears to have happened just after start of the game probably using saved language selection from previous time.
Is there any eduactiv8.mo file in /usr/share/locale/? If the files have not been installed there, I can check for them but still will have to crash the game, maybe a little bit more gracefully unless I'll keep the English version separately as default.

**Comment by glixx** [comment]
Output is on switching language. The second start is impossible.

**Comment by imiolek-ireneusz** [comment]
Is that when run form a built package or from the source?
If from a package, where do you move the locale files when installing? /usr/share/locale/? or somewhere else?

**Comment by imiolek-ireneusz** [comment]
Regarding your last message. Not sure what the installer does on Mageia, but when installing, maybe you need to manually create the directory structure when not present for any language the package is attempting to install?

**Comment by glixx** [comment]
> Could the locale files within the package be left where they are

Yes in your case, because settings of some distrubutions skip installation of locales if they are extra, but you need all locales to switch between them in GUI.

But you can improve algorithm. As you can see %_install_langs from /etc/rpm/macros has all English locales and your locale. So dialog of langs can contents only available locales if MO file is exist.

**Comment by imiolek-ireneusz** [comment]
I'd rather keep all the languages, so kids, for instance, can learn Spanish or other language for that matter even though their system is not necessarily supporting that language out of the box. And that lets me get away with redesigning the way language selections are displayed, saving myself some time here :)

**Comment by glixx** [comment]
Ok
