### ISSUE TITLE
POT file update

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#4]
POT file are not full. Script is missing to generate POT file.

**Comment by imiolek-ireneusz** [comment]
Just tested by adding:
print(len(self.d) + len(self.b) + len(self.shape_names) + len(self.solid_names))
at the end of default.py and I'm quite suprised to see 482 words which is the same number we have on Transifex which has been set up as suggested on #8.

The line count may be a bit misleading. There are white lines, comments, some obsolete words commented out, etc. The default.py will eventually need a little bit of a clean up one day. 
When it comes to the script somehow I preferred adding words manually to the .pot as I was adding new games and used a script to add new lines to all .po files.

**Comment by glixx** [comment]
Please check this strings to add into POT file or delete from default.py:

"Violet"
"Catalan clock"
"Apply"
"Nothing here yet..."
"v.%s"
"Decimals"
"Complete the alphabet using letters from the middle line"
"minutes"
"Find and separate the Even Numbers from the Odd Numbers in the above series."
"Re-arrange the above letters so they are in the alphabetical order."
"Re-arrange the above numbers so they are in the ascending order."
"Re-arrange the above numbers so they are in the right order"
"Rearrange the numbers so they are in the right order"
"Expand fractions"
"Learn to count"
"hours"
"To expand a fraction multiply the numerator and the denominator by the same number. Change the multiplicand to see what happens."

**Comment by imiolek-ireneusz** [comment]
I will look into that next week. Currently I haven't got access to my development machine.

**Comment by glixx** [comment]
All other strings are present in POT file except list above. So they are obsoleted or forgotten for translation. No reasons to check all strings, just from list above.
