### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by ale3andro** [imiolek-ireneusz/eduActiv8#40]
Hello Ireneusz,
in the latest deb package of Eduactiv8 (4.20.01) (Greek version) some of the activities are not working as expected (for instance the super market basket activity).
The error reported is the following:
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Some images from the activity and the error:
https://i.imgur.com/1iNAuZu.png
https://i.imgur.com/cACuGEw.png

**Comment by imiolek-ireneusz** [comment]
Hi,
Thank you for reporting this issue. I'll have to look into this, for some reason running the same version from source does not cause the issue reported. But the deb package does.
Please let me know if you come across any more issues like that one. This particular problem has been resolved but I'll have to find some spare time to make more changes and rebuild everything again.
