### ISSUE TITLE
Pronounce is not in use

### ISSUE THREAD

**Issue by glixx** [imiolek-ireneusz/eduActiv8#6]
Program does not use pronounce from i18n/custom/ru.py for:

dp["a4a_animals"] 
dp["a4a_sport"]
dp["a4a_body"]
dp["a4a_people"]
dp["a4a_food"]
dp["a4a_clothes_n_accessories"]
dp["a4a_actions"]
dp["a4a_construction"]
dp["a4a_nature"]
dp["a4a_jobs"]
dp["a4a_fruit_n_veg"]
dp["a4a_transport"]

**Comment by glixx** [comment]
Not fixed for time games.

**Comment by glixx** [comment]
Please reopen.

**Comment by imiolek-ireneusz** [comment]
I was under the impression that I managed to solve this one. I will look into the clock activities to check what is going on there. Thanks for pointing it out.
